.TH LS 1
.SH NAME
ls \- list files
.SH SYNOPSIS
.B ls
[
.B -adlt/R
]
[
.B -f
.I format
]
[
.I file ...
]
.SH OPERATION
List files in the given directories and the other given files themselves, or . if no file given. If the -a flag not given, exclude files whose name\'s first character is \'.\'.
.SS FLAGS
.TP
.B a
Include dotfiles
.TP
.B d
List directories themselves, rather than files in them
.TP
.B l
Long format; see below
.TP
.B t
Sort by modification time, rather than name
.TP
.B /
Print full path name, rather than just last part
.TP
.B R
List deeply
.SS LONG FORMAT
In long mode, ls prints more properties of each file, which are determined by the format, thus:
.TP
.B %%, %n, %t
Literal \'%\', newline, tab
.TP
.B %d
Number of device what holds file
.TP
.B %i
Inode number
.TP
.B %p
Unix mode in octal
.TP
.B %P
Unix mode in --- format
.TP
.B %l
Number of links
.TP
.B %o, %g
Owner uid, gid
.TP
.B %m
Modification time, seconds since epoch
.TP
.B %v
Device minor number
.TP
.B %V
Device major number
.TP
.B %z
File size, bytes
.TP
.B %N
File name; full path if -/ flag given
